version: "3.7"


services:
  app:
    build:
      context: .
    container_name: pizza-shop-backend
    volumes:
      - ./dist:/app
    restart: on-failure
    command: ["java", "-jar", "project-0.0.1-SNAPSHOT.jar"]
    depends_on:
      - db
    ports:
      - "8080:8080"
    networks:
      - pizzaShopNetwork
  db:
    image: mysql
    container_name: pizza-database
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: pizza
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - "3306:3306"
    volumes:
      - /pizzaShop:/var/lib/mysql
    networks:
      - pizzaShopNetwork
  web:
    ports:
      - "4200:4200"
    stdin_open: true
    tty: true
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    restart: on-failure
    depends_on:
      - db
      - app
    container_name: pizza-shop-frontend
    command: node --max-old-space-size=8192 node_modules/@angular/cli/bin/ng serve --host 0.0.0.0 --disable-host-check
    volumes:
      - ./frontend/src:/app/src
    networks:
      - pizzaShopNetwork
  nginx:
    image: nginx:alpine
    container_name: pizza-shop-nginx
    ports:
      - "80:80"
    restart: on-failure
    depends_on:
      - app
      - db
      - web
    volumes:
      - ./nginx/nginx.dev.conf:/etc/nginx/conf.d/default.conf
    networks:
      - pizzaShopNetwork
networks:
  pizzaShopNetwork:
    driver: bridge
