version: "3.7"


services:
  app:
    build:
      context: .
    container_name: pizza-shop-backend
    volumes:
      - ./dist:/app
    restart: on-failure
    command: ["java", "-jar", "project-0.0.1-SNAPSHOT.jar"]
    depends_on:
      - db
    ports:
      - "8080:8080"
  db:
    image: mysql
    container_name: pizza-database
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: pizza
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - "3306:3306"
    volumes:
      - /pizzaShop:/var/lib/mysql
  nginx:
    image: nginx:alpine
    container_name: pizza-shop-nginx
    ports:
    - "80:80"
    restart: on-failure
    depends_on:
      - app
      - db
      - web
    volumes:
    - ./nginx/nginx.conf:/etc/nginx/conf.d/nginx.conf
  web:
    build:
      context: ./PizzaShopAngular
      dockerfile: Dockerfile.prod
    restart: on-failure
    depends_on:
      - db
      - app
    container_name: pizza-shop-frontend
    command: ng build --prod
