# node
FROM node:13.12.0-alpine as builder

# copy
# RUN mkdir -p /app
# WORKDIR /app
# COPY . .
# COPY package*.json ./
mkdir /var/cache/nginx

# angular
# RUN npm i -g npm
# RUN npm cache clean --force
# RUN npm install -g @angular/cli@11.2.11
# RUN node --max-old-space-size=8192 node_modules/@angular/cli/bin/ng build

# nginx
FROM nginx:alpine

